apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sqzt3l1e9-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sqzt3l1e9-java-quarkus-gitops